### ISSUE TITLE
Making History Parts

### ISSUE THREAD

**Issue by lordcirth** [ChrisAdderley/CommunityTechTree#38]
The 1.825m fairing is placed in Advanced Construction(90) by default.  It should probably be in between the 1.25m and 2.5m in Aviation(45) or possibly General Construction(45).

The Wolfhound engine is nearly a straight upgrade to the Poodle, and probably shouldn't be in the same node.  I would move it up 1 or 2 notches, IMHO.

**Comment by ChrisAdderley** [comment]
This is out of scope for this project. The goal is only to provide a generic set of nodes, not change the tree.
