### ISSUE TITLE
Usage Issue

### ISSUE THREAD

**Issue by Phelidai** [ChrisAdderley/CommunityTechTree#51]
When using Community Tech Tree in tandom with the full compliment of Near Future mods, none of the generated nodes have their associated textures or parts. It appears that the NEar Future parts are attempting to move to the new nodes, (They are gone from the standard tree), but do not show up in the new tree. Used a new savegame to test. Will include log and screenshot.

[KSP.log](https://github.com/ChrisAdderley/CommunityTechTree/files/4333301/KSP.log)

![Tech Tree Error](https://user-images.githubusercontent.com/61567118/76689730-0b0d4280-65f6-11ea-90ee-b1f8d7e795da.PNG)

**Comment by sick13** [comment]
I think you messed up the installation, try again...can't say for sure but there are texture load errors for the CTT and judging from the errors you have them mixed up, also you have old module manager in
"[LOG 13:07:18.410] Load(Assembly): Near Future Aero/ModuleManager.3.1.3" remove all old ones 3.1.3 and 4.1.3 just leave one in GameData [4.1.3] then try again

**Comment by Phelidai** [comment]
Well, I noticed I had the Tech Tree in a subfolder on accident, and pulling it out fixed the textures. But the missing parts are still missing.

**Comment by ChrisAdderley** [comment]
Your install is a big mess. As per the install instructions for all of my mods:
```
To install, place the GameData folder inside your Kerbal Space Program folder. If asked to overwrite files, please do so.

NOTE: Do NOT rename or move folders within the GameData folder - this mod uses absolute paths to assets and will break if this happens.
```
Your log shows entries like:
`GameData/Near Future Exploration/NearFutureExploration/Parts/FuelTank/nfex-fueltank-stack-medium-1/nfex-fueltank-stack-medium-1`
and
`GameData/Near Future Electrical/CommunityResourcePack/CommonResources/LqdAmmonia`
This means you have placed each mod within its own user-created inside GameData, which is super bad. The correct version of those entries would be
`GameData/NearFutureExploration/Parts/FuelTank/nfex-fueltank-stack-medium-1/nfex-fueltank-stack-medium-1`
and
`GameData/CommunityResourcePack/CommonResources/LqdAmmonia`

**Comment by Phelidai** [comment]
Ah, must have had some settings changed during zip extraction, as I used the same method on my secondary computer. Thought I checked for install mistakes. Will fix and check.

**Comment by Phelidai** [comment]
Working as intended now! Will be careful to check installs in the future! Thank you for you patience.

**Comment by ChrisAdderley** [comment]
Glad to hear that fixed it :)
