### ISSUE TITLE
Incompatible with CKAN for KSPv.1.10+

### ISSUE THREAD

**Issue by hoovler** [ChrisAdderley/CommunityTechTree#52]
### Issue

Cannot install `CommunityTechTree` to `KSP v.1.10+` using **CKAN**.

#### Reproduction

1. Get the latest version of **CKAN**
2. Get the latest version of **Kerbal Space Program** (`v.1.10+`)
3. Try to install `CommunityTechTree` plugin using **CKAN**.  It will be incompatible.

#### Current Work-Around

Install `CommunityTechTree` from the [`dev` branch](https://github.com/ChrisAdderley/CommunityTechTree/tree/dev).

---

### Analysis

It looks like @ChrisAdderley's ["_Mark for 1.10.0_" branch](https://github.com/ChrisAdderley/CommunityTechTree/commit/44de37542b572176697edebba6389365c05217ab) merged into `dev` corrected the issue for that branch, but **CKAN** uses the `master` branch for its versioning information.

#### Suggested Solution

Either of the following, most likely the latter:

1. Merge @ChrisAdderley's ["_Mark for 1.10.0_" branch](https://github.com/ChrisAdderley/CommunityTechTree/commit/44de37542b572176697edebba6389365c05217ab) (`44de37542b572176697edebba6389365c05217ab`) into `master`.
2. Merge the `dev` branch into `master`.

**Comment by ChrisAdderley** [comment]
Well yes, but I'm not pushing updates to anything until the next minor version of KSP.

**Comment by hoovler** [comment]
@ChrisAdderley, my apologies!  In that case, I'll close the issue!
